# Uncomment this line to define a global platform for your project

platform :ios, '7.1'
inhibit_all_warnings!

def import_pods
    pod 'AFNetworking', '~> 2.6.0'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'SDWebImage', '~>3.7'
end


target ‘Demo_Dribbble’ do
    import_pods
end
